version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_USER=default
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - PORT=3000
  redis:
    image: "redis:latest"
    environment:
      - REDIS_USER=default
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      